name: unison-code-explorer
license: BSD3
default-extensions:

  # Notable

  - StrictData

  # Other

  - DataKinds
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DerivingStrategies
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - RankNTypes
  - ScopedTypeVariables
  - TypeFamilies
  - TypeOperators

ghc-options: -Wall
dependencies:

  # Notable

  - aeson-pretty
  - gitrev
  - servant-server
  - unison-core
  - unison-parser-typechecker
  - wai
  - wai-cors
  - warp

  # Other

  - aeson
  - async
  - base
  - bytestring
  - containers
  - directory
  - filepath
  - hashable
  - lens
  - mtl
  - optparse-applicative
  - random
  - safe-exceptions
  - stm
  - text
  - time
  - transformers
  - unordered-containers

library:
  source-dirs: src
executables:
  unison-code-explorer:
    source-dirs: misc
    main: Main.hs
    ghc-options: -threaded -rtsopts
    dependencies:
      - unison-code-explorer
