resolver: lts-12.5
extra-deps:
  - git: git@github.com:unisonweb/unison.git
    commit: 'bca45bf81ab4924229afd468b8359e80d71f285a'
    subdirs:
      - parser-typechecker
      - yaks/easytest
      - yaks/haskeline

  # Needed for unison
  - base58-bytestring-0.1.0
  - strings-1.1
  - relation-0.2.1
  - guid-0.1.0
